### ISSUE TITLE
Stable chromium version

### ISSUE THREAD

**Issue by daycode** [andDevW/getChromium#21]
Add option to download the stable version of chromium

**Comment by andDevW** [comment]
It doesn't update often enough to need an app.
François Beaufort's [downloadchromium](https://download-chromium.appspot.com/?platform=Android&type=continuous) has the Last Known Good Revision of Chromium. 
F-droid might still publish the old versions of getChromium(1, 1.2) that offer the option.

**Comment by daycode** [comment]
Just a little question. Why did you remove that in new versions ? 🤔

**Comment by andDevW** [comment]
I'm a big believer in Ken Thompson's UNIX philosophy.
"Make each program do one thing well. To do a new job, build afresh rather than complicate old programs by adding new "features"." Perpetually installing build revision 382014(a build the same age as this app) is not the good thing I want my app to do.
