### ISSUE TITLE
Directly download from f-droid and differences from other packages

### ISSUE THREAD

**Issue by jarry9** [andDevW/getChromium#22]
Hi,

First thank you for this development...

1- Why you don't add the chromium-apk directly to f-droid. So we can directly download the app from f-droid like other apps.

2- There is another android app for same purpose: https://github.com/adolfintel/chromiumUpdater You know what is the difference with your app?

Thanks in advance...

**Comment by andDevW** [comment]
Thanks, I'm glad you appreciate the app.
1. It's not possible to distribute Chromium's latest build via APK because the only way to update is by installing a newer version of the latest build. 
2. My app was the first Chromium installer app for Android. Aside from that, the other app you mentioned requires you to either leave 'Unknown sources' enabled, or have root on your device. Both of these conditions present ongoing security problems.
