### ISSUE TITLE
Leaves apks behind

### ISSUE THREAD

**Issue by rugk** [andDevW/getChromium#5]
In my case these two apks were left behind after installing chromium:
- /storage/emulated/0/Android/data/com.anddevw.getchromium/files/getChromium/chrome-android/apks/ChromePublic.apk
- /storage/emulated/0/Android/data/com.anddevw.getchromium/files/getChromium/chrome-android/apks/ContentShell.apk

BTW what is ContentShell and what does it have to so worth Charmin Chromium?

**Comment by andDevW** [comment]
The Chromium apk(ChromePublic) is the app that getChromium installs.
There is an unused apk for ContentShell, which can optionally be used with Chromium.
Here's one use for the ContentShell:
https://www.chromium.org/developers/how-tos/run-chromium-with-flags
There's a lot more information available here: https://www.chromium.org/Home

**Comment by rugk** [comment]
Thanks for the explanation. However this does not solve the issue with the apks, which are left behind. They use useless memory.

I think the apks should be deleted after a successful installation. So please reopen this issue.

**Comment by andDevW** [comment]
Thanks, you make a very good point. 
I'll have the apk files automatically deleted after successful installation. 
Will be included in the next release.

**Comment by andDevW** [comment]
Ok, after some changes I've managed to reduce the memory used by nearly half without sacrificing any usability. With v3.2 the ContentShell.apk is immediately deleted which reduces the storage used by 39.7MB. After extensive testing I've determined that retaining the ChromePublic.apk in cache turns out to be crucial to proper app function. Removing the cache will invariably lead to instances where the APK is downloaded more than once, which can be expensive in dollars/euro. Currently v3.2 is taking up 51.38MB with the latest ChromePublic.apk always cached, which means it will never have to download the larger package (combined ChromePublic.apk and ContentShell.apk = 69.6MB) twice. 

In the end storage alone is cheaper than the alternative combination of increased bandwith + increased battery drain + increased time downloading.
